// This file has been modified from the original WalkerKnapp/devolay version by the vicvalentim/devolay community-maintained fork (2026).

plugins {
    id 'java'
    id 'application'
}

sourceCompatibility = JavaVersion.VERSION_1_8
application {
    mainClass = 'me.walkerknapp.devolayexamples.SendAudioExample'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":devolay-java")
    implementation group: 'org.bytedeco', name: 'ffmpeg-platform', version: '4.2.1-1.5.2'
    //runtimeOnly project(":devolay-natives")
}

task executeSendAudioExample(type:JavaExec) {
    mainClass = "me.walkerknapp.devolayexamples.SendAudioExample"
    classpath = sourceSets.main.runtimeClasspath
}

task executeRecvExample(type:JavaExec) {
    mainClass = "me.walkerknapp.devolayexamples.RecvExample"
    classpath = sourceSets.main.runtimeClasspath
}

task executeSendVideoExample(type:JavaExec) {
    mainClass = "me.walkerknapp.devolayexamples.SendVideoExample"
    classpath = sourceSets.main.runtimeClasspath
}

task executeRecordingExample(type:JavaExec) {
    mainClass = "me.walkerknapp.devolayexamples.recording.RecordingExample"
    classpath = sourceSets.main.runtimeClasspath
}

task executeMonitorExample(type:JavaExec) {
    mainClass = "me.walkerknapp.devolayexamples.MonitorExample"
    classpath = sourceSets.main.runtimeClasspath
}

task executeFrameSyncExample(type:JavaExec) {
    mainClass = "me.walkerknapp.devolayexamples.FrameSyncExample"
    classpath = sourceSets.main.runtimeClasspath
}
